name: Release
on:
  push:
    branches: [ release ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker build --label org.opencontainers.image.revision=${{github.sha}} --iidfile example.id . &&
        docker tag    "$(cat example.id)" "ghcr.io/gugod/election-day-bot:latest" &&
        docker login  "ghcr.io" -u gugod --password-stdin <<<"${{secrets.GHCR_TOKEN}}" &&
        docker push   "ghcr.io/gugod/election-day-bot:latest" &&
        docker logout "ghcr.io"
