name: Tweet

on:
  schedule:
    - cron: 43 7 * * *

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
    - name: local post
      uses: mosteo-actions/docker-run@v1
      with:
        image: 'docker://ghcr.io/gugod/election-day-bot:latest'
