name: Tweet

on:
  schedule:
    - cron: '0 23 * * *'

jobs:
  tweet:
    container:
      image: perl:5.32
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: release
      - run: date
      - run: date
        env:
          TZ: Asia/Taipei
      - run: cpanm -q --notest --no-man-pages --installdeps .
      - name: tweet
        env:
          TWITTER_TOKENS: ${{ secrets.TWITTER_TOKENS }}
        run: perl tweet.pl -y --github-secret
